### ISSUE TITLE
Bug with cachedmethod function

### ISSUE THREAD

**Issue by owocado** [awolverp/cachebox#10]
Hello and greetings,

According to documentation, it says that `cachedmethod` function ignores `self` parameter but as I'm using it currently, it somehow requires it:
![image](https://github.com/user-attachments/assets/2f24e3aa-e7ae-419b-bc82-fa53c33098b2)

Is this a bug in cachebox v4.1.0?

**Comment by awolverp** [comment]
I just noticed this problem. When we use a class as a decorator, this problem will happen.

```python
class wrap:
    def __init__(self, func) -> None:
        self.func = func

    def __call__(self, *args, **kwds):
        return self.func(*args, **kwds)


class Test:
    @wrap
    def test(self, *args, **kwargs):
        pass


a = Test()
a.test()
# TypeError: Test.test() missing 1 required positional argument: 'self'
```

I will fix this problem in cachebox ASAP.

**Comment by owocado** [comment]
oh interesting, thank you very much for the follow up. 👍🏼

**Comment by owocado** [comment]
Thanks 😅 and have a great day ahead!
