### ISSUE TITLE
pypi `4.2.2` release Missing wheels for `CPython 3.10+ manylinux: glibc 2.17+ x86-64`

### ISSUE THREAD

**Issue by ksquarekumar** [awolverp/cachebox#13]
First of all thanks for this amazing library 🙇‍♂️,
Version `4.2.2` onwards the wheels for [`cachebox`](https://pypi.org/project/cachebox/4.2.2/#files) do not have any `x86-64` builds beyond `CPython 3.10`, this is not the case for previous releases upto `4.2.1`, I am assuming it's still supported but somehow got missed ?
- CPython 3.11 manylinux: glibc 2.17+ x86-64
- CPython 3.12 manylinux: glibc 2.17+ x86-64
- CPython 3.13 manylinux: glibc 2.17+ x86-64

https://github.com/awolverp/cachebox/commit/cd59eafeda0647b30c554b01a204357c5b9fa2bb#diff-3ab46ee209a127470fce3c2cf106b1a1dbadbb929a4b5b13656a4bc4ce19c0b8R62 was changed to pypy3.9 and pypy3.10 for manylinux glibc ?

**Comment by ecarrara** [comment]
I'm experiencing the same issue.

**Comment by ecarrara** [comment]
@awolverp I opened a PR to fix this issue. Here is a run that test this changes: https://github.com/ecarrara/cachebox/actions/runs/11396482937/job/31710382206

Thanks for this amazing library!!! 👍

**Comment by awolverp** [comment]
Oh shit, I sorry about that I forgot them. Thank you.

@ecarrara special thanks to you for your help ❤️
