### ISSUE TITLE
Feature suggestion: layered cache

### ISSUE THREAD

**Issue by v-francoise** [awolverp/cachebox#3]
Hi!

The way I use cachetools as of today is by having a two-layered cache provided by https://pypi.org/project/CacheToolsUtils/

- a short term one using in-memory and/or file-based cache (the former for threadpool, the latter for processpool)
- a longer term one using Redis

It would be great to eventually propose these features, or at least document how we can extend your code to implement them using pure Python.

Your library looks very promising BTW :)

**Comment by awolverp** [comment]
Hi

I will add support for `pickle` that helps save objects in files.
and i will try to add Redis but not soon.

Thank you for suggestions ❤️

**Comment by awolverp** [comment]
I added support for `pickle` on version 3.1.0,
but adding Redis is time-consuming, so I close this issue.

Perhaps i will add Redis in a separate package.

**Comment by ecarrara** [comment]
I created a library that supports multi layer caching and other useful (at least for me) features. 

https://github.com/ecarrara/yapcache

@v-francoise I'm using the cachebox for the local/in-memory cache.
