### ISSUE TITLE
[Feature] ReadOnly caches

### ISSUE THREAD

**Issue by owocado** [awolverp/cachebox#6]
hello and greetings,

I have recently stumbled upon cachebox and I found it to be extremely useful library for assigning large cache of objects at much lower memory footprint. So thank you so much for making this public. :D

My question is whether there is a way currently to make Cache class read only? My use case is that I assign few variables as constants at module level in my project that should not allow any modification or mutation after assignment to prevent weird edge cases. I am using MappingProxyType for now which is in python stdlib but I find it to be rather slow on large dictionaries so this is why I opened this issue.

Thanks for reading and wish you a great day!

**Comment by awolverp** [comment]
Hello and thank you for your good idea

I will add read only caches to library as soon as possible :)

**Comment by owocado** [comment]
oh sweet, thank you @awolverp for doing this and wish you a great weekend 😄
