### ISSUE TITLE
Persistent cache

### ISSUE THREAD

**Issue by Koowah** [awolverp/cachebox#8]
Hi,

Is there a built-in way to persist decorated functions' cache ([like this](https://github.com/python-cachier/cachier?tab=readme-ov-file#pickle-core)) ? Also, can we clear a decorated function's cache [like this](https://github.com/python-cachier/cachier?tab=readme-ov-file#resetting-a-cache) ?

It would help me tremendously for my use-case : I'd like to persist some compute heavy function's results throughout multiple runs.

Thank you !
Cheers

**Comment by awolverp** [comment]
Hi,
No there's no built-in way to persist decorated functions' cache, but you can use this trick:

```python
import cachebox as cb
import atexit
import pickle
import os.path


def custom_cached(filename, cache, *args, **kwargs):
    if os.path.exists(filename):
        with open(filename, "rb") as fd:
            cache = pickle.load(fd)

    def _save_pickle():
        with open(filename, "wb") as fd:
            pickle.dump(cache, fd)

    atexit.register(_save_pickle)

    return cb.cached(cache, *args, **kwargs)


@custom_cached("file.pickle", cb.FIFOCache(0))
def factorial(n: int) -> int:
    fact = 1
    for num in range(2, n + 1):
        fact *= num
    return fact


print(factorial(20))
```

And yes you can manage decorated functions' cache like this:
```python
# clear cache
factorial.cache_clear()

# access to cache
print(factorial.cache)
```

**Comment by yuanjie-ai** [comment]
Are you planning to support Redis

**Comment by awolverp** [comment]
@yuanjie-ai No I don't have a plan to support Redis
